// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:book/config/constants/enviroment.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Enviroment.firebaseWebKey,
    appId: Enviroment.firebaseAppIdWeb,
    messagingSenderId: Enviroment.firebaseMessageSenderId,
    projectId: Enviroment.firebaseProjectId,
    authDomain: Enviroment.firebaseAuthDomain,
    databaseURL: Enviroment.firebaseDBUrl,
    storageBucket: Enviroment.firebaseStorageBucket,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Enviroment.firebaseAndroidKey,
    appId: Enviroment.firebaseAppIdAndroid,
    messagingSenderId: Enviroment.firebaseMessageSenderId,
    projectId: Enviroment.firebaseProjectId,
    databaseURL: Enviroment.firebaseDBUrl,
    storageBucket: Enviroment.firebaseStorageBucket,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Enviroment.firebaseAppleKey,
    appId: Enviroment.firebaseAppIdApple,
    messagingSenderId: Enviroment.firebaseMessageSenderId,
    projectId: Enviroment.firebaseProjectId,
    databaseURL: Enviroment.firebaseDBUrl,
    storageBucket: Enviroment.firebaseStorageBucket,
    androidClientId: Enviroment.firebaseandroidClientId,
    iosClientId: Enviroment.firebaseiosClientId,
    iosBundleId: Enviroment.firebaseiosBundleId,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: Enviroment.firebaseAppleKey,
    appId: Enviroment.firebaseAppIdApple,
    messagingSenderId: Enviroment.firebaseMessageSenderId,
    projectId: Enviroment.firebaseProjectId,
    databaseURL: Enviroment.firebaseDBUrl,
    storageBucket: Enviroment.firebaseStorageBucket,
    androidClientId: Enviroment.firebaseandroidClientId,
    iosClientId: Enviroment.firebaseiosClientId,
    iosBundleId: Enviroment.firebaseiosBundleId,
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: Enviroment.firebaseWindowsKey,
    appId: Enviroment.firebaseAppIdWindows,
    messagingSenderId: Enviroment.firebaseMessageSenderId,
    projectId: Enviroment.firebaseProjectId,
    authDomain: Enviroment.firebaseAuthDomain,
    databaseURL: Enviroment.firebaseDBUrl,
    storageBucket: Enviroment.firebaseStorageBucket,
  );
}
